### ISSUE TITLE
Built-in: Yu —— Features Tracking

### ISSUE THREAD

**Issue by sunhuachuang** [cypherlink/assassin#1]
### Chat with Friend.
- [x] main page.
- [x] chat page.
- [x] add friend page.
- [x] make friends record.
- [x] friend info show.
- [ ] auto/custom online/offine.
- [ ] friend delete.
- [ ] friend remark.
- [x] chat with plaintext.
- [ ] chat with emoji.
- [ ] chat with image.
- [ ] chat with media.
- [ ] chat with file.
- [ ] chat with voice connected.
- [ ] chat with video connected.

### Chat with Groups.
- [ ] TODO Design.
