### ISSUE TITLE
Built-in: Docs —— Features Tracking

### ISSUE THREAD

**Issue by sunhuachuang** [cypherlink/assassin#2]
### File Manager
- [x] main page.
- [ ] upload file
- [ ] new document file
- [ ] file open/preview
- [ ] file distributed storage in devices.

### Document
- [ ] markdown editor/show.
- [ ] richtext for editor
- [ ] standard output format.

### Collaboration Document
- [ ] line-lock

### Connected third-party cloud storage
- [ ] Google drive
- [ ] Dropbox

### Open share file
- [ ] TODO design.
